version: "3.9"  # optional since v1.27.0
services:
  tremap:
    restart: always
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - API_URL=${API_URL}
      # - API_USERNAME=${API_USERNAME}
      # - API_PASSWORD=${API_PASSWORD}
    build: .
    networks:
      - proxynet
    expose:
      - 8501
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tremap.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.tremap.entrypoints=http"
networks:
    proxynet:
        external:
            name: "proxynet"